### ISSUE TITLE
Did the website dead?

### ISSUE THREAD

**Issue by TRSWNCA** [windupcloud/windupcloud.github.io#4]
I bought the service for 1 yr in Dec. 2021. But now I can't event access the website. What's going on?

**Comment by turinblueice** [comment]
me too。 I can't login The WebSite。All the mirrors of Wind-Up Cloud access denied. The telegaram channel has stopped updating since Steptember 2020. What's your problem??

**Comment by windupcloud** [comment]
Hi, you must have not paid attention to the announcement.
Now the new website is http://www.yahahguide.com
You can also join the new telegarm channel https://t.me/yahaha_guide  to get the Latest news
